config/routes.rb
Rails.application.routes.draw do
  resources :coupons
  get 'products/:id', to: 'products#show', :as => :products
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users
  root :to => 'visitors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  has_many :users
  validates :code, inclusion: { in: Coupon.pluck('DISTINCT code'),
      message: "value is not a valid coupon code" }
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  after_validation :set_coupon

  belongs_to :coupon
  accepts_nested_attributes_for :coupon
  validates_associated :coupon

  def set_default_role
    self.role ||= :user
  end

  def set_coupon
    return false if errors.any?
    return false if self.coupon.nil?
    coupon = Coupon.find_by code: self.coupon.code
    self.coupon = coupon
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :admin_only

  respond_to :html

  def index
    @coupons = Coupon.all
    respond_with(@coupons)
  end

  def show
    respond_with(@coupon)
  end

  def new
    @coupon = Coupon.new
    respond_with(@coupon)
  end

  def edit
  end

  def create
    @coupon = Coupon.new(coupon_params)
    @coupon.save(validate: false)
    respond_with(@coupon)
  end

  def update
    @coupon = Coupon.find(params[:id])
    @coupon.attributes = coupon_params
    @coupon.save(validate: false)
    respond_with(@coupon)
  end

  def destroy
    @coupon.destroy
    respond_with(@coupon)
  end

  private
    def set_coupon
      @coupon = Coupon.find(params[:id])
    end

    def coupon_params
      params.require(:coupon).permit(:code, :role, :mailing_list_id, :list_group, :price)
    end

    def admin_only
      unless current_user.admin?
        redirect_to root_path, :alert => "Access denied."
      end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :identify_product

  def show
    send_file @path, :disposition => "attachment; filename=#{@file}"
  end

  private
  def identify_product
    valid_characters = "^[0-9a-zA-Z]*$".freeze
    unless params[:id].blank?
      @product_id = params[:id]
      @product_id = @product_id.tr("^#{valid_characters}", '')
    else
      raise "Filename missing"
    end
    unless params[:format].blank?
      @format = params[:format]
      @format = @format.tr("^#{valid_characters}", '')
    else
      raise "File extension missing"
    end
    @path = "app/views/products/#{@product_id}.#{@format}"
    @file = "#{@product_id}.#{@format}"
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protect_from_forgery :except => :create
  after_action :process_order, :only => :create

  def new
    build_resource({})
    yield resource if block_given?
    self.resource.coupon = Coupon.new
    respond_with self.resource
  end

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation,
      :stripe_token, {coupon_attributes: [:code]})
  end

  def process_order
    return if resource.admin?
    if resource.persisted?
      PaymentJob.perform_later(resource) unless resource.coupon.price == 0
      MailingListSignupJob.perform_later(resource)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
    @resource = User.new
    @resource.coupon = Coupon.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/views/coupons/_form.html.haml
= form_for(@coupon) do |f|
  - if @coupon.errors.any?
    #error_explanation
      %h2
        = pluralize(@coupon.errors.count, "error")
        prohibited this coupon from being saved:
      %ul
        - @coupon.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :code
    %br/
    = f.text_field :code
  .field
    = f.label :role
    %br/
    = f.text_field :role
  .field
    = f.label :mailing_list_id
    %br/
    = f.text_field :mailing_list_id
  .field
    = f.label :list_group
    %br/
    = f.text_field :list_group
  .field
    = f.label :price
    %br/
    = f.number_field :price
  .actions
    = f.submit

app/views/coupons/edit.html.haml
%h1 Editing Coupon
= render 'form'
= link_to 'Show', @coupon
|
= link_to 'Back', coupons_path

app/views/coupons/index.html.haml
%p#notice= notice
%h1 Listing Coupons
%table
  %thead
    %tr
      %th Code
      %th Role
      %th Mailing list
      %th List group
      %th Price
      %th{:colspan => "3"}
  %tbody
    - @coupons.each do |coupon|
      %tr
        %td= coupon.code
        %td= coupon.role
        %td= coupon.mailing_list_id
        %td= coupon.list_group
        %td= coupon.price
        %td= link_to 'Show', coupon
        %td= link_to 'Edit', edit_coupon_path(coupon)
        %td= link_to 'Destroy', coupon, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Coupon', new_coupon_path

app/views/coupons/new.html.haml
%h1 New Coupon
= render 'form'
= link_to 'Back', coupons_path

app/views/coupons/show.html.haml
%p#notice= notice
%p
  %strong Code:
  = @coupon.code
%p
  %strong Role:
  = @coupon.role
%p
  %strong Mailing list:
  = @coupon.mailing_list_id
%p
  %strong List group:
  = @coupon.list_group
%p
  %strong Price:
  = @coupon.price
= link_to 'Edit', edit_coupon_path(@coupon)
|
= link_to 'Back', coupons_path

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path, data: { no_turbolink: true } %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'Coupons', coupons_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_navigation_links.html.haml
%li= link_to 'About', page_path('about')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Rails Stripe Coupons"
    %meta{:content => "#{content_for?(:description) ? yield(:description) : "Rails Stripe Coupons"}", :name => "description"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = yield(:head)
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/pages/downloads.html.haml
.authform
  = form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :role => 'form', :class => 'payment-form'}) do |f|
    %h3 Free Download
    .form-group
      = f.label :email
      = f.email_field :email, class: 'form-control'
    .form-group
      = f.label :password
      = f.password_field :password, class: 'form-control'
    .form-group
      = f.label :password_confirmation
      = f.password_field :password_confirmation, class: 'form-control'
    .form-group
      %label{:for => "user_coupon_attributes_code"} Invitation code
      %input#user_coupon_attributes_code.form-control{:name => "user[coupon_attributes][code]", :type => "text"}/
    %p
      No invitation code? You can #{link_to 'purchase the book', root_path}.
    = f.submit 'Sign up', :class => 'button right'

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.haml
%h3 User
%p
  Name: #{@user.name if @user.name}
%p
  Email: #{@user.email if @user.email}

app/views/visitors/_purchase.html.haml
%br/
%a.btn.btn-primary{"data-target" => "#purchaseModal", "data-toggle" => "modal", :href => "#"} Purchase
#purchaseModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "purchaseModal", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-sm
    .modal-content
      - content_for :head do
        = render 'devise/registrations/javascript'
      .authform
        = form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :role => 'form', :class => 'payment-form'}) do |f|
          %h3 Sign up
          #stripe_error.alert.alert-danger{:style => "display:none"}
          = devise_error_messages!
          .form-group
            = f.label :email
            = f.email_field :email, class: 'form-control'
          .form-group
            = f.label :password
            = f.password_field :password, class: 'form-control'
          .form-group
            = f.label :password_confirmation
            = f.password_field :password_confirmation, class: 'form-control'
          - if resource.stripe_token
            %p Credit card acceptance is pending.
          - else
            .form-group
              = label_tag :card_number, "Credit Card Number"
              = text_field_tag :card_number, nil, name: nil, class: 'form-control', data: { stripe: 'number' }
            .form-group
              = label_tag :card_code, "Card Security Code"
              = text_field_tag :card_code, nil, name: nil, class: 'form-control', data: { stripe: 'cvc' }
            %br/
            .form-group
              = label_tag :card_month, "Card Expiry"
              = select_month nil, { use_two_digit_numbers: true}, { name: nil, data: {stripe: 'exp-month' } }
              = select_year nil, {start_year: Date.today.year, end_year: Date.today.year+10}, { name: nil, data: {stripe: 'exp-year' } }
          %br/
          = f.fields_for :coupon do |ff|
            .form-group
              = ff.label 'Coupon code'
              = ff.text_field :code, :class => 'form-control'
          = f.hidden_field :stripe_token
          = f.submit 'Sign up', :class => 'button right'

app/views/visitors/index.html.haml
%h3 Welcome
- if user_signed_in?
  - if current_user.admin?
    %h3 Admin
    %p
      = link_to 'User count:', users_path
      = User.count
  - else
    %h3 Download the book.
    = link_to 'Download PDF', products_path('product.pdf'), :class => 'btn btn-success btn-large'
- else
  %h3 Purchase the book.
  %article
    %label.amount
      = image_tag 'rubyonrails.png', size: '60x60'
      %div= Rails.application.secrets.product_title
      %div= number_to_currency(Rails.application.secrets.product_price.to_f/100)
    = render :partial => 'purchase'